services:
  backend:
    container_name: flowagora-backend
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/FlowAgora
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - flowagora-network
    restart: unless-stopped
  
  mongo:
    container_name: flowagora-mongo
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - flowagora-network
    restart: unless-stopped

networks:
  flowagora-network:
    driver: bridge

volumes:
  mongo-data:
